name:  searchable_list
description:  A Polymer sample app that shows a custom element

dependencies:
  polymer: ">=0.12.0 <0.13.0"
transformers:
- polymer:
    entry_points: web/index.html
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
